(defpackage #:msgpack-rpc-neovim
  (:use #:cl #:messagepack)
  (:export *ext-type-list*
           *ext-lookup-table*))

(defpackage #:cl-neovim
  (:use #:cl #:msgpack-rpc-neovim)
  (:export #:call/a #:call/s #:*nvim-instance*)
  (:export #:buffer-offset #:buffer-loaded-p #:buffer-clear-namespace #:buffer-virtual-text #:create-namespace #:namespaces #:buffer-attach #:buffer-detach #:buffer-commands #:call-dict-function #:commands #:client-info #:chan-info #:chans #:parse-expression #:uis #:proc-children #:proc #:buffer-keymap #:hl-by-name #:hl-by-id #:execute-lua #:keymap #:buffer-changedtick #:mode #:buffer-line-count #:buffer-lines #:buffer-var #:buffer-del-var #:buffer-option #:buffer-number #:buffer-name #:buffer-valid-p #:buffer-mark #:buffer-add-highlight #:buffer-clear-highlight #:tabpage-windows #:tabpage-var #:tabpage-del-var #:tabpage-window #:tabpage-number #:tabpage-valid-p #:ui-attach #:ui-detach #:ui-try-resize #:ui-option #:command #:feedkeys #:input #:replace-termcodes #:command-output #:eval/s #:call-function #:strwidth #:runtime-paths #:current-dir #:current-line #:del-current-line #:var #:del-var #:vvar #:option #:out-write #:err-write #:err-writeln #:buffers #:current-buffer #:windows #:current-window #:tabpages #:current-tabpage #:subscribe #:unsubscribe #:color-by-name #:color-map #:api-info #:call-atomic #:window-buffer #:window-cursor #:window-height #:window-width #:window-var #:window-del-var #:window-option #:window-position #:window-tabpage #:window-number #:window-valid-p #:buffer-line #:buffer-del-line #:buffer-line-slice #:buffer-insert #:change-directory #:report-error #:name-to-color)
(:export #:buffer-offset/a #:buffer-loaded-p/a #:buffer-clear-namespace/a #:buffer-virtual-text/a #:create-namespace/a #:namespaces/a #:buffer-attach/a #:buffer-detach/a #:buffer-commands/a #:call-dict-function/a #:commands/a #:client-info/a #:chan-info/a #:chans/a #:parse-expression/a #:uis/a #:proc-children/a #:proc/a #:buffer-keymap/a #:hl-by-name/a #:hl-by-id/a #:execute-lua/a #:keymap/a #:buffer-changedtick/a #:mode/a #:buffer-line-count/a #:buffer-lines/a #:buffer-var/a #:buffer-del-var/a #:buffer-option/a #:buffer-number/a #:buffer-name/a #:buffer-valid-p/a #:buffer-mark/a #:buffer-add-highlight/a #:buffer-clear-highlight/a #:tabpage-windows/a #:tabpage-var/a #:tabpage-del-var/a #:tabpage-window/a #:tabpage-number/a #:tabpage-valid-p/a #:ui-attach/a #:ui-detach/a #:ui-try-resize/a #:ui-option/a #:command/a #:feedkeys/a #:input/a #:replace-termcodes/a #:command-output/a #:eval/a #:call-function/a #:strwidth/a #:runtime-paths/a #:current-dir/a #:current-line/a #:del-current-line/a #:var/a #:del-var/a #:vvar/a #:option/a #:out-write/a #:err-write/a #:err-writeln/a #:buffers/a #:current-buffer/a #:windows/a #:current-window/a #:tabpages/a #:current-tabpage/a #:subscribe/a #:unsubscribe/a #:color-by-name/a #:color-map/a #:api-info/a #:call-atomic/a #:window-buffer/a #:window-cursor/a #:window-height/a #:window-width/a #:window-var/a #:window-del-var/a #:window-option/a #:window-position/a #:window-tabpage/a #:window-number/a #:window-valid-p/a #:buffer-line/a #:buffer-del-line/a #:buffer-line-slice/a #:buffer-insert/a #:change-directory/a #:report-error/a #:name-to-color/a))

